2020-10-28 17:22:29.019 - [Info] MITM Version: 1.26
2020-10-28 17:22:29.026 - [Info] Auto Access Enabled: true
2020-10-28 17:22:29.026 - [Debug] [Init] Auto Access Barrier: true
2020-10-28 17:22:29.049 - [Info] SSH man-in-the-middle server for 172.20.0.201 listening on 0.0.0.0:10000
2020-10-28 17:24:30.600 - [Debug] [Connection] Attacker connected: 190.2.137.62 | Client Identification: SSH-2.0-sshlib-0.1
2020-10-28 17:24:32.201 - [Debug] [Auth] Attacker 190.2.137.62 trying to authenticate with "password"
2020-10-28 17:24:32.202 - [Debug] [Auto Access] Attacker: 190.2.137.62, Threshold: 1, Attempts: 1
2020-10-28 17:24:32.203 - [Debug] [Auto Access] Compromising the honeypot
2020-10-28 17:24:32.203 - [Debug] [Auto Access] Adding the following credentials: "root:root"
2020-10-28 17:24:32.518 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-28 17:24:32.519 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.201
2020-10-28 17:24:32.631 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-28 17:24:49.403 - [Debug] [Connection] Attacker closed connection
2020-10-28 17:24:49.410 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-28 17:24:49.411 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-28 17:25:25.951 - [Debug] [Connection] Attacker connected: 59.125.28.51 | Client Identification: SSH-2.0-OpenSSH_7.9p1 Raspbian-10+deb10u2
2020-10-28 17:25:25.999 - [Debug] [Connection] Attacker connected: 59.125.28.51 | Client Identification: SSH-2.0-OpenSSH_7.9p1 Raspbian-10+deb10u2
2020-10-28 17:25:27.267 - [Debug] [Auth] Attacker 59.125.28.51 trying to authenticate with "none"
2020-10-28 17:25:27.268 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 17:25:27.315 - [Debug] [Auth] Attacker 59.125.28.51 trying to authenticate with "none"
2020-10-28 17:25:27.315 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 17:25:27.728 - [Debug] [Auth] Attacker 59.125.28.51 trying to authenticate with "password"
2020-10-28 17:25:27.729 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-28 17:25:27.730 - [Debug] [Auth] Attacker: 59.125.28.51 has so far made 1 attempts. Remaining: 5 attempts
2020-10-28 17:25:27.778 - [Debug] [Auth] Attacker 59.125.28.51 trying to authenticate with "password"
2020-10-28 17:25:27.779 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-28 17:25:27.780 - [Debug] [Auth] Attacker: 59.125.28.51 has so far made 1 attempts. Remaining: 5 attempts
2020-10-28 17:25:28.139 - [Debug] [Connection] Attacker closed the connection
2020-10-28 17:25:28.188 - [Debug] [Connection] Attacker closed the connection
