2020-10-28 23:53:01.812 - [Info] MITM Version: 1.26
2020-10-28 23:53:01.819 - [Info] Auto Access Enabled: true
2020-10-28 23:53:01.819 - [Debug] [Init] Auto Access Barrier: true
2020-10-28 23:53:01.846 - [Info] SSH man-in-the-middle server for 172.20.0.201 listening on 0.0.0.0:10000
2020-10-28 23:53:54.577 - [Debug] [Connection] Attacker connected: 171.227.209.44 | Client Identification: SSH-2.0-AsyncSSH_2.1.0
2020-10-28 23:53:56.406 - [Debug] [Auth] Attacker 171.227.209.44 trying to authenticate with "none"
2020-10-28 23:53:56.407 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 23:53:56.923 - [Debug] [Auth] Attacker 171.227.209.44 trying to authenticate with "password"
2020-10-28 23:53:56.925 - [Debug] [Auto Access] Attacker: 171.227.209.44, Threshold: 1, Attempts: 1
2020-10-28 23:53:56.925 - [Debug] [Auto Access] Compromising the honeypot
2020-10-28 23:53:56.925 - [Debug] [Auto Access] Adding the following credentials: "root:@"
2020-10-28 23:53:57.247 - [Debug] [Auth] Valid credentials - Password Authentication
2020-10-28 23:53:57.247 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.201
2020-10-28 23:53:57.347 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2020-10-28 23:53:59.459 - [Debug] [Connection] Client error on ssh server
2020-10-28 23:53:59.460 - [Debug] [Connection] Attacker closed connection
2020-10-28 23:53:59.467 - [Debug] [LXC] Container's OpenSSH server ended connection
2020-10-28 23:53:59.468 - [Debug] [LXC] Container's OpenSSH server closed connection
2020-10-28 23:55:32.933 - [Debug] [Connection] Attacker connected: 171.227.209.44 | Client Identification: SSH-2.0-AsyncSSH_2.1.0
2020-10-28 23:55:34.903 - [Debug] [Auth] Attacker 171.227.209.44 trying to authenticate with "none"
2020-10-28 23:55:34.903 - [Debug] [Auth] Attacker authentication error: No authentication method provided
2020-10-28 23:55:35.543 - [Debug] [Auth] Attacker 171.227.209.44 trying to authenticate with "password"
2020-10-28 23:55:35.544 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2020-10-28 23:55:35.545 - [Debug] [Auth] Attacker: 171.227.209.44 has so far made 1 attempts. Remaining: 5 attempts
2020-10-28 23:55:36.046 - [Debug] [Connection] Attacker closed the connection
